# Generated by Django 5.1.1 on 2025-04-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único del producto', max_length=50, null=True, unique=True),
        ),
    ]
